//! CLI command implementations.

mod alerts;
mod attest;
mod audit;
mod baseline;
mod check;
mod common;
mod config;
mod diff;
mod doctor;
mod explain;
mod hooks;
mod init;
mod inspect;
mod log;
mod maintenance;
mod recover;
pub(crate) mod selftest;
mod setup;
mod status;
mod test_alert;
mod update;
mod watch;
mod welcome;
mod why;
mod why_silent;

pub(crate) use alerts::cmd_alerts;
pub(crate) use attest::cmd_attest;
pub(crate) use audit::cmd_audit;
pub(crate) use baseline::cmd_baseline;
pub(crate) use check::{cmd_check, cmd_check_live, CheckOpts};
pub(crate) use config::cmd_config;
pub(crate) use diff::cmd_diff;
pub(crate) use doctor::cmd_doctor;
pub(crate) use explain::cmd_explain;
pub(crate) use hooks::cmd_hooks;
pub(crate) use init::cmd_init;
pub(crate) use inspect::cmd_inspect;
pub(crate) use log::cmd_log;
pub(crate) use maintenance::cmd_maintenance;
pub(crate) use recover::cmd_recover;
pub(crate) use selftest::cmd_selftest;
pub(crate) use setup::cmd_setup;
pub(crate) use status::cmd_status;
pub(crate) use test_alert::cmd_test_alert;
pub(crate) use update::cmd_update;
pub(crate) use watch::cmd_watch;
pub(crate) use welcome::cmd_welcome;
pub(crate) use why::cmd_why;
pub(crate) use why_silent::cmd_why_silent;
